language: java

sudo: false

os:
  - linux
  - osx

notifications:
 email: 
  recipients:
     - sw2a307b@gmail.com
  on_success: always # default: change
  on_failure: always # default: always
      
      
webhooks: https://discordapp.com/api/webhooks/421123184214016028/EdNfakhRzwJObGJOAXKRA5AdiXSW3HaplQcHh7DyD3P_e4ymUc2PP5gS2OfD2REoqk2t
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
