version: "{build}"

image: Visual Studio 2017

build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
notifications:

  # Email
  - provider: Email
    to:
      - sw2a307b@gmail.com
